{   bazLib / bazAction
    Copyright (C) 2021-2099 Baz Cuda
    https://github.com/BazzaCuda/bazLib

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307, USA
}
unit bazFuncDefs;

interface

{ THIS UNIT IS GENERATED BY bazActionGen.exe. AMEND THE bazActionDefs.txt FILE TO REGENERATE THIS UNIT FOR DIFFERENT FUNCTION TYPES AND FUNCTION SIGNATURES }
{ These are project-specific datatypes added via identically-named descendants of bazAction.TAction }

type
  TVoid = record end;

  TFunc<T> = reference to function: T;
  TAFuncNoParam             <TResult> = reference to function():                                                        TResult;
  TAFuncString              <TResult> = reference to function(const aString: string):                                   TResult;
  TAFuncInteger             <TResult> = reference to function(const aInteger: integer):                                 TResult;
  TAFuncIntegerString       <TResult> = reference to function(const aInteger: integer; const aString: string):          TResult;
  TAFuncStringInteger       <TResult> = reference to function(const aString: string; const aInteger: integer):          TResult;
  TAFuncBoolean             <TResult> = reference to function(const aBoolean: boolean):                                 TResult;
  TAFuncWord                <TResult> = reference to function(const aWORD: WORD):                                       TResult;
  TAFuncCardinal            <TResult> = reference to function(const aCardinal: cardinal):                               TResult;
  TAFuncStringString        <TResult> = reference to function(const aString1: string; const aString2: string):          TResult;
  TAFuncStringBoolean       <TResult> = reference to function(const aString: string; const aBoolean: boolean):          TResult;

  TAProcNoParam              = reference to procedure()                                                        ;
  TAProcString               = reference to procedure(const aString: string)                                   ;
  TAProcInteger              = reference to procedure(const aInteger: integer)                                 ;
  TAProcIntegerString        = reference to procedure(const aInteger: integer; const aString: string)          ;
  TAProcStringInteger        = reference to procedure(const aString: string; const aInteger: integer)          ;
  TAProcBoolean              = reference to procedure(const aBoolean: boolean)                                 ;
  TAProcWord                 = reference to procedure(const aWORD: WORD)                                       ;
  TAProcCardinal             = reference to procedure(const aCardinal: cardinal)                               ;
  TAProcStringString         = reference to procedure(const aString1: string; const aString2: string)          ;
  TAProcStringBoolean        = reference to procedure(const aString: string; const aBoolean: boolean)          ;

  TAFuncBooleanString       <TResult> = reference to function(const aBoolean: boolean; const aString: string):          TResult;

  TAProcBooleanString        = reference to procedure(const aBoolean: boolean; const aString: string)          ;

implementation

end.
